### PR TITLE
Update core/pom.xml gson 2.8.4 to 2.8.5

### PR DESCRIPTION
**Pull request by frikit**
Please see comment below.

### CODE REVIEW

**Comment by frikit** [comment]
Update gson version in order to fix number format exception in intellij idea where java version is 11-ea

https://github.com/google/gson/issues/1469
https://community.sonarsource.com/t/sonarlint-does-not-work-in-intellij-2019-1-eap-jbr11/6786

**Comment by henryju** [comment]
Merged, thanks!

**Comment by Veranicus** [comment]
Hello, I still have this problem with SonarLint and Intellij 2019.03 and jdk 11.

**Comment by henryju** [comment]
This is because no new version of SonarLint for IntelliJ has been released since this fix has been merged. The fix was done in the shared library, now we have to release a new version.

I will try to do that next week. You can follow this specific ticket to be notified of the progress:
https://jira.sonarsource.com/browse/SLI-333

**Pull request merged**
