### PR TITLE
SLCORE-437 Provide a cli to extract rules metadata from plugins

### PR DESCRIPTION
**Pull request by henryju**

### CODE REVIEW

**Comment by duncanp-sonar** [comment]
@henryju as discussed, could you add the internal key property please?

Also, I think the manifest is missing the `Main-Class` setting.

**Comment by henryju** [comment]
@duncanp-sonar I have added the internalKey.

> Also, I think the manifest is missing the Main-Class setting.
The manifest entry is only in the "fat JAR" (the one with name xxx-jar-with-dependencies.jar)

**Review by damien-urruty-sonarsource — APPROVED** [review]
I have one concern. The `RulesDefinitionExtractor.extractRules()` method returns a List<SonarLintRuleDefinition> that is used to generate the json output. It means that SonarLintRuleDefinition becomes a contract, and we could easily forget that, change the name of a field, add or remove one and it would break on the reader side. 
I would suggest to introduce another data type (yes, again) in this new module. It would also help clearly identify what fields are needed by consumers

**Comment by henryju** [comment]
> It means that SonarLintRuleDefinition becomes a contract

We discussed that with @duncanp-sonar and we agreed this is good enough as a first start. It will only be used at build time by the SLVS bubble, so a breaking change in the output is not a big deal. We will see if we need to introduce a more specific contract later.

**Comment by duncanp-sonar** [comment]
> It will only be used at build time

I'll make sure it causes a build failure in SLVS if the file doesn't contain the expected fields so we can't miss it on our side.

**Pull request merged**
